#!/bin/bash

echo 'do you really want to rsync --DELETE from Y2kMadData to B2kMadBackup?'

sudo echo 'ok then, thanks BOSS'

cat > rotate.txt <<EOF
"bin/.B2kMadBackup.txt" {
	rotate 5
	dateext
	missingok
	daily
	dateformat --%Y-%m-%d
}
EOF

echo 'Rotating log files if needed'

logrotate -f rotate.txt

rm rotate.txt


echo 'Initiating rsync Backup from Y2kMadData to B2kMadBackup'

sudo rsync -ax --delete --progress --stats --log-file='/home/y2k/bin/.B2kMadBackup.txt' /media/.Y2kMadData/ /media/B2kMadBackup

wait
