#!/bin/bash

echo 'do you really want to RESTORE!!!!! rsync from B2kMadBackup to Y2kMadData?'

sudo echo 'ok then, thanks BOSS'


echo 'Initiating rsync restore from B2kMadBackup to Y2kMadData'

sudo rsync -ax --progress --stats --log-file='/home/y2k/bin/.B2kMadRestore.txt' /media/B2kMadBackup/ /media/.Y2kMadData

read
wait
